server:
  port: 9999
  servlet:
    context-path: /
spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: EtlSupervisorScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.41:3306/etl_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: leo
    password: Leo123456!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: EtlSupervisorDS
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
  output:
    ansi:
      enabled: detect
  thymeleaf:
    cache: true
    mode: HTML
  mvc:
    static-path-pattern: /**
    favicon:
      enabled: false
  mail:
    host: smtp.mxhichina.com
    port: 465
    username: leo.jie@datarealglobal.com
    password: Yyf5211314!
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        starttls:
          enable: true
          required: true
logging:
  path: log/
  file: log/EtlSupervisor.log
